modLoader="javafml"
loaderVersion="[44,)"
license="GPL 3.0"

[[mods]]
modId="unlimitedmaxhealth"
version="1.0"
displayName="Unlimited MaxHealth"
logoFile="logo.png"
authors="LitnhJacuzzi"
description='''
Breaks entity max health limitation at client side.
'''

[[dependencies.unlimitedmaxhealth]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.unlimitedmaxhealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="CLIENT"
