modLoader="javafml"
loaderVersion="[34,)"
license="GPL 3.0"

[[mods]]
modId="unlimitedmaxhealth"
version="1.0"
displayName="Unlimited MaxHealth"
authors="LitnhJacuzzi"
description='''
Break the entity health limitation at client side.
'''

[[dependencies.unlimitedmaxhealth]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.unlimitedmaxhealth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,1.17)"
    ordering="NONE"
    side="CLIENT"
